name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e 'ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --exclude 'private_key.pem' . ubuntu@$SERVER_IP:backend-pace
        ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$SERVER_IP "sudo apt-get remove -y libnode-dev && curl -fsSL https://deb.nodesource.com/setup_14.x | sudo bash - && sudo apt-get install -y nodejs && cd backend-pace && npm i && pm2 restart npm test"
