name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 400 private_key.pem
        ssh -i private_key.pem -r . ubuntu@$SERVER_IP:backend-pace
        ssh -i private_key.pem ubuntu@$SERVER_IP "cd backend-pace && npm ci && pm2 restart npm test"
